apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    istio:
      gateway.knative-serving.knative-ingress-gateway: istio-ingressgateway.istio-system-reto.svc.cluster.local
      local-gateway.knative-serving.knative-local-gateway: knative-local-gateway.istio-system-reto.svc.cluster.local
  deployments:
  - annotations:
      sidecar.istio.io/inject: "true"
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    name: activator
  - annotations:
      sidecar.istio.io/inject: "true"
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    name: autoscaler
  ingress:
    istio:
      enabled: true
